spring:
  cloud:
    gcp:
      project-id: "my-wallet-357616"
      credentials:
        location: "file:sa-my-wallet-357616-33dc3721140f.json"
        scopes: "https://www.googleapis.com/auth/datastore"
      datastore:
        namespace: "expense-app"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
app:
  domain:
    categories: FOOD, ENTERTAINMENT, UTILITIES, HOME, OTHER
